//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identity) DeepCopyInto(out *Identity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in *Identity) DeepCopy() *Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UsersRef != nil {
		in, out := &in.UsersRef, &out.UsersRef
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GroupsRef != nil {
		in, out := &in.GroupsRef, &out.GroupsRef
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.GroupRef != nil {
		in, out := &in.GroupRef, &out.GroupRef
		*out = new(string)
		**out = **in
	}
	if in.ServicePrincipals != nil {
		in, out := &in.ServicePrincipals, &out.ServicePrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServicePrincipalsRef != nil {
		in, out := &in.ServicePrincipalsRef, &out.ServicePrincipalsRef
		*out = new(string)
		**out = **in
	}
	if in.SkipQueryWhenTargetHasData != nil {
		in, out := &in.SkipQueryWhenTargetHasData, &out.SkipQueryWhenTargetHasData
		*out = new(bool)
		**out = **in
	}
	if in.QueryInterval != nil {
		in, out := &in.QueryInterval, &out.QueryInterval
		*out = new(string)
		**out = **in
	}
	if in.FailOnEmpty != nil {
		in, out := &in.FailOnEmpty, &out.FailOnEmpty
		*out = new(bool)
		**out = **in
	}
	if in.ActiveAccount != nil {
		in, out := &in.ActiveAccount, &out.ActiveAccount
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalFields != nil {
		in, out := &in.AdditionalFields, &out.AdditionalFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(Identity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
