//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.HashAlgorithm != nil {
		in, out := &in.HashAlgorithm, &out.HashAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.ApprovalField != nil {
		in, out := &in.ApprovalField, &out.ApprovalField
		*out = new(string)
		**out = **in
	}
	if in.OldHashField != nil {
		in, out := &in.OldHashField, &out.OldHashField
		*out = new(string)
		**out = **in
	}
	if in.NewHashField != nil {
		in, out := &in.NewHashField, &out.NewHashField
		*out = new(string)
		**out = **in
	}
	if in.PauseAnnotation != nil {
		in, out := &in.PauseAnnotation, &out.PauseAnnotation
		*out = new(string)
		**out = **in
	}
	if in.DetailedCondition != nil {
		in, out := &in.DetailedCondition, &out.DetailedCondition
		*out = new(bool)
		**out = **in
	}
	if in.ApprovalMessage != nil {
		in, out := &in.ApprovalMessage, &out.ApprovalMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
